"""Add include_in_strategy to invested

Revision ID: 0a8eb5a3bd70
Revises: d177dc0f5075
Create Date: 2025-12-16 09:55:35.304240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8eb5a3bd70'
down_revision = 'd177dc0f5075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invested', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_in_strategy', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invested', schema=None) as batch_op:
        batch_op.drop_column('include_in_strategy')

    # ### end Alembic commands ###
