"""add_strategy2_indicators_and_strategy_id

Revision ID: 28551fae5330
Revises: 
Create Date: 2026-06-10 09:14:33.569001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28551fae5330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # indicators S2 columns already exist (added by db.create_all on app start)
    # Only the strategy_id columns for percentile/score/ranking need migrating.

    with op.batch_alter_table('percentile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.String(length=20), nullable=False, server_default='strategy1'))
        batch_op.create_index('idx_percentile_strategy', ['strategy_id', 'percentile_date'], unique=False)

    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.String(length=20), nullable=False, server_default='strategy1'))
        batch_op.create_index('idx_ranking_strategy', ['strategy_id', 'ranking_date'], unique=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.String(length=20), nullable=False, server_default='strategy1'))
        batch_op.create_index('idx_score_strategy', ['strategy_id', 'score_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index('idx_score_strategy')
        batch_op.drop_column('strategy_id')

    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.drop_index('idx_ranking_strategy')
        batch_op.drop_column('strategy_id')

    with op.batch_alter_table('percentile', schema=None) as batch_op:
        batch_op.drop_index('idx_percentile_strategy')
        batch_op.drop_column('strategy_id')

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_column('quality_z_score')
        batch_op.drop_column('momentum_12m')
        batch_op.drop_column('log_price_vol_corr')
        batch_op.drop_column('scaled_turnover')
        batch_op.drop_column('sortino_ratio')
        batch_op.drop_column('nse_norm_momentum')
        batch_op.drop_column('mansfield_rs')
        batch_op.drop_column('adx_14')

    # ### end Alembic commands ###
