"""Auto migration

Revision ID: 2975697a4102
Revises: 
Create Date: 2026-02-15 09:16:01.971220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2975697a4102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index('idx_indicator_tradingsymbol_date', ['tradingsymbol', 'date'], unique=False)

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index('idx_marketdata_tradingsymbol_date', ['tradingsymbol', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index('idx_marketdata_tradingsymbol_date')

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index('idx_indicator_tradingsymbol_date')

    # ### end Alembic commands ###
