"""Auto migration

Revision ID: 2b8d7c180a0a
Revises: ec783b888853
Create Date: 2026-01-04 08:00:32.197227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d7c180a0a'
down_revision = 'ec783b888853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('avg_score', schema=None) as batch_op:
    #     # batch_op.create_index('idx_score', ['composite_score'], unique=False)
    #     batch_op.create_index('idx_score_date', ['score_date'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avg_score', schema=None) as batch_op:
        batch_op.drop_index('idx_score_date')
        batch_op.drop_index('idx_score')

    # ### end Alembic commands ###
