"""Auto migration

Revision ID: 307d7187b904
Revises: 7ae50fb1b1af
Create Date: 2026-01-05 10:09:16.941297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307d7187b904'
down_revision = '7ae50fb1b1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_ranking',
    sa.Column('tradingsymbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('composite_score', sa.FLOAT(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('ranking_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('tradingsymbol', 'ranking_date')
    )
    # ### end Alembic commands ###
