"""Auto migration

Revision ID: 32199048f3a8
Revises: 2b8d7c180a0a
Create Date: 2026-01-04 08:03:50.623390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32199048f3a8'
down_revision = '2b8d7c180a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('avg_score', schema=None) as batch_op:
    #     batch_op.create_index('idx_score_date', ['score_date'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avg_score', schema=None) as batch_op:
        batch_op.drop_index('idx_score_date')

    # ### end Alembic commands ###
