"""Auto migration

Revision ID: 37163b18bc2c
Revises: d5ee6f6ff535
Create Date: 2026-01-04 08:06:27.701041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37163b18bc2c'
down_revision = 'd5ee6f6ff535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avg_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_score'))
        batch_op.drop_index(batch_op.f('idx_score_date'))
        batch_op.create_index('idx_avg_score', ['composite_score'], unique=False)
        batch_op.create_index('idx_avg_score_date', ['score_date'], unique=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index('idx_score_date', ['score_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index('idx_score_date')

    with op.batch_alter_table('avg_score', schema=None) as batch_op:
        batch_op.drop_index('idx_avg_score_date')
        batch_op.drop_index('idx_avg_score')
        batch_op.create_index(batch_op.f('idx_score_date'), ['score_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_score'), ['composite_score'], unique=False)

    # ### end Alembic commands ###
