"""Auto migration

Revision ID: 3fad4c65fc0b
Revises: cc42e13dfc38
Create Date: 2026-02-13 20:45:03.379744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fad4c65fc0b'
down_revision = 'cc42e13dfc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('percentile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_trend', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trend_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_momentum', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('momentum_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_efficiency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('efficiency_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_structure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('structure_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalty', sa.Float(), nullable=True))
        batch_op.drop_column('trend_start_rank')
        batch_op.drop_column('structure_bb_rank')
        batch_op.drop_column('percent_b')
        batch_op.drop_column('efficiency_rank')
        batch_op.drop_column('rsi_signal_ema_3')
        batch_op.drop_column('trend_extension_rank')
        batch_op.drop_column('price_vol_correlation')
        batch_op.drop_column('trend_rank')
        batch_op.drop_column('risk_adjusted_return')
        batch_op.drop_column('ppoh_12_26_9')
        batch_op.drop_column('rvol')
        batch_op.drop_column('structure_rank')
        batch_op.drop_column('bbb_20_2')
        batch_op.drop_column('distance_from_ema_200')
        batch_op.drop_column('ppo_12_26_9')
        batch_op.drop_column('momentum_rsi_rank')
        batch_op.drop_column('price_vol_corr_rank')
        batch_op.drop_column('momentum_ppo_rank')
        batch_op.drop_column('ema_50_slope')
        batch_op.drop_column('distance_from_ema_50')
        batch_op.drop_column('rvolume_rank')
        batch_op.drop_column('momentum_ppoh_rank')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('structure_score')
        batch_op.drop_column('vol_score')
        batch_op.drop_column('momentum_score')
        batch_op.drop_column('trend_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trend_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('momentum_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('vol_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('structure_score', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('percentile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('momentum_ppoh_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rvolume_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('distance_from_ema_50', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ema_50_slope', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('momentum_ppo_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_vol_corr_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('momentum_rsi_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ppo_12_26_9', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('distance_from_ema_200', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('bbb_20_2', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('structure_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rvol', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ppoh_12_26_9', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('risk_adjusted_return', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trend_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_vol_correlation', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trend_extension_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rsi_signal_ema_3', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('efficiency_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('percent_b', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('structure_bb_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trend_start_rank', sa.FLOAT(), nullable=True))
        batch_op.drop_column('penalty')
        batch_op.drop_column('structure_percentile')
        batch_op.drop_column('factor_structure')
        batch_op.drop_column('volume_percentile')
        batch_op.drop_column('factor_volume')
        batch_op.drop_column('efficiency_percentile')
        batch_op.drop_column('factor_efficiency')
        batch_op.drop_column('momentum_percentile')
        batch_op.drop_column('factor_momentum')
        batch_op.drop_column('trend_percentile')
        batch_op.drop_column('factor_trend')
        batch_op.drop_column('close')

    # ### end Alembic commands ###
