"""Auto migration

Revision ID: 5239d82ccd87
Revises: 
Create Date: 2025-12-23 18:18:34.271468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5239d82ccd87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsi_signal_ema_3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_adjusted_return', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_vol_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.drop_column('vol_score')
        batch_op.drop_column('rank_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_position', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('vol_score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('rank')
        batch_op.drop_column('final_vol_score')
        batch_op.drop_column('risk_adjusted_return')
        batch_op.drop_column('rsi_signal_ema_3')

    # ### end Alembic commands ###
