"""Add amount and buy range to actions

Revision ID: 85cb856b17c1
Revises: 946437ef6813
Create Date: 2025-12-16 08:22:07.474192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cb856b17c1'
down_revision = '946437ef6813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buy_price_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buy_price_max', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('buy_price_max')
        batch_op.drop_column('buy_price_min')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
