"""Auto migration

Revision ID: 8d0e36581b28
Revises: 307d7187b904
Create Date: 2026-02-08 15:38:07.376084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0e36581b28'
down_revision = '307d7187b904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roc_60', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('roc_125', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('atr_spike', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_column('atr_spike')
        batch_op.drop_column('roc_125')
        batch_op.drop_column('roc_60')

    # ### end Alembic commands ###
