"""Auto migration

Revision ID: 917da05e1fef
Revises: 
Create Date: 2026-02-12 08:44:17.116881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917da05e1fef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('momentum_3m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('momentum_6m', sa.Float(), nullable=True))

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factor_trend', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_momentum', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_efficiency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('factor_structure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trend_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('momentum_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('efficiency_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('structure_rank', sa.Float(), nullable=True))
        batch_op.drop_column('final_trend_score')
        batch_op.drop_column('final_momentum_score')
        batch_op.drop_column('final_structure_score')
        batch_op.drop_column('final_vol_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_vol_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('final_structure_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('final_momentum_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('final_trend_score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('structure_rank')
        batch_op.drop_column('volume_rank')
        batch_op.drop_column('efficiency_rank')
        batch_op.drop_column('momentum_rank')
        batch_op.drop_column('trend_rank')
        batch_op.drop_column('factor_structure')
        batch_op.drop_column('factor_volume')
        batch_op.drop_column('factor_efficiency')
        batch_op.drop_column('factor_momentum')
        batch_op.drop_column('factor_trend')

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_column('momentum_6m')
        batch_op.drop_column('momentum_3m')

    # ### end Alembic commands ###
