"""Add portfolio management tables

Revision ID: 946437ef6813
Revises: 
Create Date: 2025-12-16 08:08:54.598894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946437ef6813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_column('volume_20')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_20', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
