"""Auto migration

Revision ID: 9a8a0c16f9e5
Revises: 0a8eb5a3bd70
Create Date: 2025-12-17 22:42:41.506115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8a0c16f9e5'
down_revision = '0a8eb5a3bd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_actions_date'))
        batch_op.drop_index(batch_op.f('idx_actions_type'))

    op.drop_table('actions')
    with op.batch_alter_table('invested', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_invested_symbol'))

    op.drop_table('invested')
    op.drop_table('risk_config')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vol_sma_20', sa.Float(), nullable=True))
        batch_op.drop_column('volume_sma_20')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_sma_20', sa.FLOAT(), nullable=True))
        batch_op.drop_column('vol_sma_20')

    op.create_table('risk_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('initial_capital', sa.FLOAT(), nullable=False),
    sa.Column('current_capital', sa.FLOAT(), nullable=False),
    sa.Column('risk_per_trade', sa.FLOAT(), nullable=False),
    sa.Column('max_positions', sa.INTEGER(), nullable=False),
    sa.Column('buffer_percent', sa.FLOAT(), nullable=False),
    sa.Column('exit_threshold', sa.FLOAT(), nullable=False),
    sa.Column('stop_loss_multiplier', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invested',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tradingsymbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('instrument_token', sa.INTEGER(), nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=10), nullable=True),
    sa.Column('buy_price', sa.FLOAT(), nullable=False),
    sa.Column('num_shares', sa.INTEGER(), nullable=False),
    sa.Column('buy_date', sa.DATE(), nullable=False),
    sa.Column('atr_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('initial_stop_loss', sa.FLOAT(), nullable=False),
    sa.Column('current_stop_loss', sa.FLOAT(), nullable=False),
    sa.Column('current_score', sa.FLOAT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('include_in_strategy', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tradingsymbol')
    )
    with op.batch_alter_table('invested', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_invested_symbol'), ['tradingsymbol'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_date', sa.DATE(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tradingsymbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('units', sa.INTEGER(), nullable=False),
    sa.Column('expected_price', sa.FLOAT(), nullable=True),
    sa.Column('composite_score', sa.FLOAT(), nullable=True),
    sa.Column('swap_from_symbol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('swap_from_units', sa.INTEGER(), nullable=True),
    sa.Column('swap_from_price', sa.FLOAT(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('executed', sa.BOOLEAN(), nullable=True),
    sa.Column('executed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('buy_price_min', sa.FLOAT(), nullable=True),
    sa.Column('buy_price_max', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_actions_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_actions_date'), ['action_date'], unique=False)

    # ### end Alembic commands ###
