"""Auto migration

Revision ID: a735c30a07a5
Revises: cb80d57162ec
Create Date: 2026-01-05 08:39:22.061991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a735c30a07a5'
down_revision = 'cb80d57162ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('sector')
        batch_op.drop_column('industry')
        batch_op.drop_column('market_cap')

    # ### end Alembic commands ###
