"""Auto migration

Revision ID: cb80d57162ec
Revises: 37163b18bc2c
Create Date: 2026-01-05 08:29:50.997548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb80d57162ec'
down_revision = '37163b18bc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketcap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('regularmarketprice', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alltimehigh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alltimelow', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sharesoutstanding', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('floatshares', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heldpercentinsiders', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heldpercentinstitutions', sa.Float(), nullable=True))
        batch_op.drop_column('held_percent_institutions')
        batch_op.drop_column('float_shares')
        batch_op.drop_column('regularMarketPrice')
        batch_op.drop_column('all_time_low')
        batch_op.drop_column('held_percent_insiders')
        batch_op.drop_column('shares_outstanding')
        batch_op.drop_column('all_time_high')
        batch_op.drop_column('market_cap')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('all_time_high', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('shares_outstanding', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('held_percent_insiders', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('all_time_low', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('regularMarketPrice', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('float_shares', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('held_percent_institutions', sa.FLOAT(), nullable=True))
        batch_op.drop_column('heldpercentinstitutions')
        batch_op.drop_column('heldpercentinsiders')
        batch_op.drop_column('floatshares')
        batch_op.drop_column('sharesoutstanding')
        batch_op.drop_column('alltimelow')
        batch_op.drop_column('alltimehigh')
        batch_op.drop_column('regularmarketprice')
        batch_op.drop_column('marketcap')

    # ### end Alembic commands ###
