"""Auto migration

Revision ID: cc42e13dfc38
Revises: 917da05e1fef
Create Date: 2026-02-13 09:33:39.767099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc42e13dfc38'
down_revision = '917da05e1fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trend_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('momentum_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vol_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('structure_score', sa.Float(), nullable=True))
        batch_op.drop_column('factor_momentum')
        batch_op.drop_column('structure_rank')
        batch_op.drop_column('efficiency_rank')
        batch_op.drop_column('factor_structure')
        batch_op.drop_column('factor_efficiency')
        batch_op.drop_column('momentum_rank')
        batch_op.drop_column('factor_volume')
        batch_op.drop_column('factor_trend')
        batch_op.drop_column('trend_rank')
        batch_op.drop_column('volume_rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trend_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('factor_trend', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('factor_volume', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('momentum_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('factor_efficiency', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('factor_structure', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('efficiency_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('structure_rank', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('factor_momentum', sa.FLOAT(), nullable=True))
        batch_op.drop_column('structure_score')
        batch_op.drop_column('vol_score')
        batch_op.drop_column('momentum_score')
        batch_op.drop_column('trend_score')

    # ### end Alembic commands ###
