"""Auto migration

Revision ID: d5ee6f6ff535
Revises: 32199048f3a8
Create Date: 2026-01-04 08:04:41.535401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ee6f6ff535'
down_revision = '32199048f3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('score', schema=None) as batch_op:
    #     batch_op.create_index('idx_score_date', ['score_date'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index('idx_score_date')

    # ### end Alembic commands ###
