"""Auto migration

Revision ID: dde463ee7bf5
Revises: ce6aca747d25
Create Date: 2026-02-28 09:56:41.833930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde463ee7bf5'
down_revision = 'ce6aca747d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_indicator_tradingsymbol_date'))
        batch_op.drop_column('instrument_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_token', sa.INTEGER(), nullable=False))
        batch_op.create_index(batch_op.f('idx_indicator_tradingsymbol_date'), ['tradingsymbol', 'date'], unique=False)

    # ### end Alembic commands ###
