"""Auto migration

Revision ID: e5ebc298d82b
Revises: 
Create Date: 2025-12-29 21:05:47.750057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ebc298d82b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_from_ema_50', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trend_start_rank', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_ranking_score'))
        batch_op.drop_column('final_momentum_score')
        batch_op.drop_column('final_vol_score')
        batch_op.drop_column('final_structure_score')
        batch_op.drop_column('rank')
        batch_op.drop_column('final_trend_score')
        batch_op.drop_column('composite_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composite_score', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('final_trend_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('final_structure_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('final_vol_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('final_momentum_score', sa.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_ranking_score'), ['composite_score'], unique=False)
        batch_op.drop_column('trend_start_rank')
        batch_op.drop_column('distance_from_ema_50')

    # ### end Alembic commands ###
