from marshmallow import Schema, fields

class IndicatorsSchema(Schema):
    instrument_token = fields.Int(required=True)
    tradingsymbol = fields.Str(required=True)
    date = fields.Date(required=True)
    exchange = fields.Str(required=True)

    ema_50 = fields.Float(allow_none=True) 
    ema_200 = fields.Float(allow_none=True)
    rsi_14 = fields.Float(allow_none=True)
    roc_10 = fields.Float(allow_none=True)
    roc_20 = fields.Float(allow_none=True)
    sma_20 = fields.Float(allow_none=True)
    stochk_14_3_3 = fields.Float(allow_none=True)
    stochd_14_3_3 = fields.Float(allow_none=True)
    stochh_14_3_3 = fields.Float(allow_none=True)
    ppo_12_26_9 = fields.Float(allow_none=True)
    ppoh_12_26_9 = fields.Float(allow_none=True)
    ppos_12_26_9 = fields.Float(allow_none=True)
    macd_12_26_9 = fields.Float(allow_none=True)
    macdh_12_26_9 = fields.Float(allow_none=True)
    macds_12_26_9 = fields.Float(allow_none=True)
    bbl_20_2_2 = fields.Float(allow_none=True)
    bbm_20_2_2 = fields.Float(allow_none=True)
    bbu_20_2_2 = fields.Float(allow_none=True)
    bbb_20_2_2 = fields.Float(allow_none=True)
    bbp_20_2_2 = fields.Float(allow_none=True)
    atrr_14 = fields.Float(allow_none=True)
    rsi_signal_ema_3 = fields.Float(allow_none=True)
    volume_sma_20 = fields.Float(allow_none=True)
    price_vol_correlation = fields.Float(allow_none=True)
    percent_b = fields.Float(allow_none=True)
    ema_50_slope = fields.Float(allow_none=True)
    distance_from_ema_200 = fields.Float(allow_none=True)
    risk_adjusted_return = fields.Float(allow_none=True)
    rvol = fields.Float(allow_none=True)
    volume_20 = fields.Float(allow_none=True)
