from .instrument_routes import blp as instruments_bp
from .marketdata_routes import blp as marketdata_bp
from .indicators_routes import blp as indicators_bp
from .percentile_routes import blp as percentile_bp
from .init_routes import blp as init_bp
from .score_routes import blp as score_bp
from .app_routes import blp as app_bp
from .ranking_routes import blp as ranking_bp
from .strategy_routes import blp as strategy_bp
from .investment_routes import blp as investment_bp